package org.onvif.ver20.ptz.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-02-20T00:15:06.074+01:00
 * Generated source version: 3.1.5
 * 
 */
@WebServiceClient(name = "PtzService", 
                  wsdlLocation = "file:/home/flavio/workspace_bosc/onvif/onvif-ws-client/src/main/cxf/ver20/ptz/wsdl/ptz.wsdl",
                  targetNamespace = "http://www.onvif.org/ver20/ptz/wsdl") 
public class PtzService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.onvif.org/ver20/ptz/wsdl", "PtzService");
    public final static QName PtzPort = new QName("http://www.onvif.org/ver20/ptz/wsdl", "PtzPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/flavio/workspace_bosc/onvif/onvif-ws-client/src/main/cxf/ver20/ptz/wsdl/ptz.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PtzService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/flavio/workspace_bosc/onvif/onvif-ws-client/src/main/cxf/ver20/ptz/wsdl/ptz.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PtzService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PtzService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PtzService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public PtzService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PtzService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PtzService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns PTZ
     */
    @WebEndpoint(name = "PtzPort")
    public PTZ getPtzPort() {
        return super.getPort(PtzPort, PTZ.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PTZ
     */
    @WebEndpoint(name = "PtzPort")
    public PTZ getPtzPort(WebServiceFeature... features) {
        return super.getPort(PtzPort, PTZ.class, features);
    }

}
