package org.onvif.ver10.device.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-02-19T23:51:26.996+01:00
 * Generated source version: 3.1.5
 * 
 */
@WebServiceClient(name = "OnvifService", 
                  wsdlLocation = "file:/home/flavio/workspace_bosc/onvif/onvif-ws-client/src/main/cxf/ver10/device/wsdl/devicemgmt.wsdl",
                  targetNamespace = "http://www.onvif.org/ver10/device/wsdl") 
public class OnvifService extends javax.xml.ws.Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.onvif.org/ver10/device/wsdl", "OnvifService");
    public final static QName OnvifEndpoint = new QName("http://www.onvif.org/ver10/device/wsdl", "OnvifEndpoint");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/flavio/workspace_bosc/onvif/onvif-ws-client/src/main/cxf/ver10/device/wsdl/devicemgmt.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OnvifService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/flavio/workspace_bosc/onvif/onvif-ws-client/src/main/cxf/ver10/device/wsdl/devicemgmt.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OnvifService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OnvifService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OnvifService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public OnvifService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public OnvifService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public OnvifService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns Device
     */
    @WebEndpoint(name = "OnvifEndpoint")
    public Device getOnvifEndpoint() {
        return super.getPort(OnvifEndpoint, Device.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Device
     */
    @WebEndpoint(name = "OnvifEndpoint")
    public Device getOnvifEndpoint(WebServiceFeature... features) {
        return super.getPort(OnvifEndpoint, Device.class, features);
    }

}
