package org.onvif.ver10.media.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-02-20T00:14:59.619+01:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://www.onvif.org/ver10/media/wsdl", name = "Media")
@XmlSeeAlso({org.oasis_open.docs.wsrf.bf_2.ObjectFactory.class, org.w3._2004._08.xop.include.ObjectFactory.class, ObjectFactory.class, org.onvif.ver10.schema.ObjectFactory.class, org.oasis_open.docs.wsn.b_2.ObjectFactory.class, org.oasis_open.docs.wsn.t_1.ObjectFactory.class, org.w3._2003._05.soap_envelope.ObjectFactory.class, org.w3._2005._05.xmlmime.ObjectFactory.class})
public interface Media {

    /**
     * This operation removes a PTZConfiguration from an existing media profile. If the media profile
     * does not contain a PTZConfiguration, the operation has no effect. The removal shall be persistent.
     */
    @WebMethod(operationName = "RemovePTZConfiguration", action = "http://www.onvif.org/ver10/media/wsdl/RemovePTZConfiguration")
    @RequestWrapper(localName = "RemovePTZConfiguration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.RemovePTZConfiguration")
    @ResponseWrapper(localName = "RemovePTZConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.RemovePTZConfigurationResponse")
    public void removePTZConfiguration(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * This operation removes a VideoSourceConfiguration from an existing media profile. If the
     * media profile does not contain a VideoSourceConfiguration, the operation has no effect. The removal shall be persistent. Video source configurations should only be removed after removing a
     * VideoEncoderConfiguration from the media profile.
     */
    @WebMethod(operationName = "RemoveVideoSourceConfiguration", action = "http://www.onvif.org/ver10/media/wsdl/RemoveVideoSourceConfiguration")
    @RequestWrapper(localName = "RemoveVideoSourceConfiguration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.RemoveVideoSourceConfiguration")
    @ResponseWrapper(localName = "RemoveVideoSourceConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.RemoveVideoSourceConfigurationResponse")
    public void removeVideoSourceConfiguration(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * This command stop multicast streaming using a specified media profile of a device
     */
    @WebMethod(operationName = "StopMulticastStreaming", action = "http://www.onvif.org/ver10/media/wsdl/StopMulticastStreaming")
    @RequestWrapper(localName = "StopMulticastStreaming", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.StopMulticastStreaming")
    @ResponseWrapper(localName = "StopMulticastStreamingResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.StopMulticastStreamingResponse")
    public void stopMulticastStreaming(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * This operation creates a new empty media profile. The media profile shall be created in the
     * device and shall be persistent (remain after reboot). A created profile shall be deletable and a device shall set the “fixed” attribute to false in the
     * returned Profile.
     */
    @WebMethod(operationName = "CreateProfile", action = "http://www.onvif.org/ver10/media/wsdl/CreateProfile")
    @RequestWrapper(localName = "CreateProfile", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.CreateProfile")
    @ResponseWrapper(localName = "CreateProfileResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.CreateProfileResponse")
    @WebResult(name = "Profile", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
    public org.onvif.ver10.schema.Profile createProfile(
        @WebParam(name = "Name", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String name,
        @WebParam(name = "Token", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String token
    );

    /**
     * This operation adds a VideoSourceConfiguration to an existing media profile. If such a
     * configuration exists in the media profile, it will be replaced. The change shall be persistent.
     */
    @WebMethod(operationName = "AddVideoSourceConfiguration", action = "http://www.onvif.org/ver10/media/wsdl/AddVideoSourceConfiguration")
    @RequestWrapper(localName = "AddVideoSourceConfiguration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.AddVideoSourceConfiguration")
    @ResponseWrapper(localName = "AddVideoSourceConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.AddVideoSourceConfigurationResponse")
    public void addVideoSourceConfiguration(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String profileToken,
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String configurationToken
    );

    /**
     * If the video encoder configuration token is already known, the encoder configuration can be fetched through the GetVideoEncoderConfiguration command.
     */
    @WebMethod(operationName = "GetVideoEncoderConfiguration", action = "http://www.onvif.org/ver10/media/wsdl/GetVideoEncoderConfiguration")
    @RequestWrapper(localName = "GetVideoEncoderConfiguration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetVideoEncoderConfiguration")
    @ResponseWrapper(localName = "GetVideoEncoderConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetVideoEncoderConfigurationResponse")
    @WebResult(name = "Configuration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
    public org.onvif.ver10.schema.VideoEncoderConfiguration getVideoEncoderConfiguration(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String configurationToken
    );

    /**
     * Returns the capabilities of the media service. The result is returned in a typed answer.
     */
    @WebMethod(operationName = "GetServiceCapabilities", action = "http://www.onvif.org/ver10/media/wsdl/GetServiceCapabilities")
    @RequestWrapper(localName = "GetServiceCapabilities", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetServiceCapabilities")
    @ResponseWrapper(localName = "GetServiceCapabilitiesResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetServiceCapabilitiesResponse")
    @WebResult(name = "Capabilities", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
    public org.onvif.ver10.media.wsdl.Capabilities getServiceCapabilities();

    /**
     * This operation returns the available options (supported values and ranges for video encoder 
     * 				configuration parameters) when the video encoder parameters are reconfigured. 
     * 				For JPEG, MPEG4 and H264 extension elements have been defined that provide additional information. A device must provide the 
     * 				XxxOption information for all encodings supported and should additionally provide the corresponding XxxOption2 information.
     * 				This response contains the available video encoder configuration options. If a video encoder configuration is specified, 
     * 				the options shall concern that particular configuration. If a media profile is specified, the options shall be 
     * 				compatible with that media profile. If no tokens are specified, the options shall be considered generic for the device.
     * 			
     */
    @WebMethod(operationName = "GetVideoEncoderConfigurationOptions", action = "http://www.onvif.org/ver10/media/wsdl/GetVideoEncoderConfigurationOptions")
    @RequestWrapper(localName = "GetVideoEncoderConfigurationOptions", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetVideoEncoderConfigurationOptions")
    @ResponseWrapper(localName = "GetVideoEncoderConfigurationOptionsResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetVideoEncoderConfigurationOptionsResponse")
    @WebResult(name = "Options", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
    public org.onvif.ver10.schema.VideoEncoderConfigurationOptions getVideoEncoderConfigurationOptions(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String configurationToken,
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * Get the OSDs.
     */
    @WebMethod(operationName = "GetOSDs", action = "http://www.onvif.org/ver10/media/wsdl/GetOSDs")
    @RequestWrapper(localName = "GetOSDs", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetOSDs")
    @ResponseWrapper(localName = "GetOSDsResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetOSDsResponse")
    @WebResult(name = "OSDs", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
    public java.util.List<org.onvif.ver10.schema.OSDConfiguration> getOSDs(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String configurationToken
    );

    /**
     * This operation removes an AudioEncoderConfiguration from an existing media profile. If the
     * media profile does not contain an AudioEncoderConfiguration, the operation has no effect.
     * The removal shall be persistent.
     */
    @WebMethod(operationName = "RemoveAudioEncoderConfiguration", action = "http://www.onvif.org/ver10/media/wsdl/RemoveAudioEncoderConfiguration")
    @RequestWrapper(localName = "RemoveAudioEncoderConfiguration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.RemoveAudioEncoderConfiguration")
    @ResponseWrapper(localName = "RemoveAudioEncoderConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.RemoveAudioEncoderConfigurationResponse")
    public void removeAudioEncoderConfiguration(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * This operation requests all audio encoder configurations of a device that are compatible with a certain media profile. Each of the returned configurations shall be a valid input parameter for the AddAudioSourceConfiguration command on the media profile. The result varies depending on the capabilities, configurations and settings in the device.
     */
    @WebMethod(operationName = "GetCompatibleAudioEncoderConfigurations", action = "http://www.onvif.org/ver10/media/wsdl/GetCompatibleAudioEncoderConfigurations")
    @RequestWrapper(localName = "GetCompatibleAudioEncoderConfigurations", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetCompatibleAudioEncoderConfigurations")
    @ResponseWrapper(localName = "GetCompatibleAudioEncoderConfigurationsResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetCompatibleAudioEncoderConfigurationsResponse")
    @WebResult(name = "Configurations", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
    public java.util.List<org.onvif.ver10.schema.AudioEncoderConfiguration> getCompatibleAudioEncoderConfigurations(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * The GetAudioEncoderConfiguration command fetches the encoder configuration if the audio encoder configuration token is known.
     */
    @WebMethod(operationName = "GetAudioEncoderConfiguration", action = "http://www.onvif.org/ver10/media/wsdl/GetAudioEncoderConfiguration")
    @RequestWrapper(localName = "GetAudioEncoderConfiguration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetAudioEncoderConfiguration")
    @ResponseWrapper(localName = "GetAudioEncoderConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetAudioEncoderConfigurationResponse")
    @WebResult(name = "Configuration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
    public org.onvif.ver10.schema.AudioEncoderConfiguration getAudioEncoderConfiguration(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String configurationToken
    );

    /**
     * If the audio output configuration token is already known, the output configuration can be fetched through the GetAudioOutputConfiguration command.
     */
    @WebMethod(operationName = "GetAudioOutputConfiguration", action = "http://www.onvif.org/ver10/media/wsdl/GetAudioOutputConfiguration")
    @RequestWrapper(localName = "GetAudioOutputConfiguration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetAudioOutputConfiguration")
    @ResponseWrapper(localName = "GetAudioOutputConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetAudioOutputConfigurationResponse")
    @WebResult(name = "Configuration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
    public org.onvif.ver10.schema.AudioOutputConfiguration getAudioOutputConfiguration(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String configurationToken
    );

    /**
     * This operation modifies an audio output configuration. The ForcePersistence flag indicates if
     * the changes shall remain after reboot of the device.
     */
    @WebMethod(operationName = "SetAudioOutputConfiguration", action = "http://www.onvif.org/ver10/media/wsdl/SetAudioOutputConfiguration")
    @RequestWrapper(localName = "SetAudioOutputConfiguration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.SetAudioOutputConfiguration")
    @ResponseWrapper(localName = "SetAudioOutputConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.SetAudioOutputConfigurationResponse")
    public void setAudioOutputConfiguration(
        @WebParam(name = "Configuration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        org.onvif.ver10.schema.AudioOutputConfiguration configuration,
        @WebParam(name = "ForcePersistence", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        boolean forcePersistence
    );

    /**
     * A client uses the GetSnapshotUri command to obtain a JPEG snapshot from the
     * device. The returned URI shall remain valid indefinitely even if the profile is changed. The
     * ValidUntilConnect, ValidUntilReboot and Timeout Parameter shall be set accordingly
     * (ValidUntilConnect=false, ValidUntilReboot=false, timeout=PT0S). The URI can be used for
     * acquiring a JPEG image through a HTTP GET operation. The image encoding will always be
     * JPEG regardless of the encoding setting in the media profile. The Jpeg settings
     * (like resolution or quality) may be taken from the profile if suitable. The provided
     * image will be updated automatically and independent from calls to GetSnapshotUri.
     */
    @WebMethod(operationName = "GetSnapshotUri", action = "http://www.onvif.org/ver10/media/wsdl/GetSnapshotUri")
    @RequestWrapper(localName = "GetSnapshotUri", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetSnapshotUri")
    @ResponseWrapper(localName = "GetSnapshotUriResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetSnapshotUriResponse")
    @WebResult(name = "MediaUri", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
    public org.onvif.ver10.schema.MediaUri getSnapshotUri(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * This operation removes a VideoEncoderConfiguration from an existing media profile. If the
     * media profile does not contain a VideoEncoderConfiguration, the operation has no effect. The removal shall be persistent.
     */
    @WebMethod(operationName = "RemoveVideoEncoderConfiguration", action = "http://www.onvif.org/ver10/media/wsdl/RemoveVideoEncoderConfiguration")
    @RequestWrapper(localName = "RemoveVideoEncoderConfiguration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.RemoveVideoEncoderConfiguration")
    @ResponseWrapper(localName = "RemoveVideoEncoderConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.RemoveVideoEncoderConfigurationResponse")
    public void removeVideoEncoderConfiguration(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * This operation requests a URI that can be used to initiate a live media stream using RTSP as
     * the control protocol. The returned URI shall remain valid indefinitely even if the profile is
     * changed. The ValidUntilConnect, ValidUntilReboot and Timeout Parameter shall be set
     * accordingly (ValidUntilConnect=false, ValidUntilReboot=false, timeout=PT0S). 
     * 				The correct syntax for the StreamSetup element for these media stream setups defined in 5.1.1 of the streaming specification are as follows:
     * 				
     * 				
     * If a multicast stream is requested the VideoEncoderConfiguration, AudioEncoderConfiguration and MetadataConfiguration element inside the corresponding 
     * media profile must be configured with valid multicast settings.
     * For full compatibility with other ONVIF services a device should not generate Uris longer than
     * 128 octets.
     */
    @WebMethod(operationName = "GetStreamUri", action = "http://www.onvif.org/ver10/media/wsdl/GetStreamUri")
    @RequestWrapper(localName = "GetStreamUri", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetStreamUri")
    @ResponseWrapper(localName = "GetStreamUriResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetStreamUriResponse")
    @WebResult(name = "MediaUri", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
    public org.onvif.ver10.schema.MediaUri getStreamUri(
        @WebParam(name = "StreamSetup", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        org.onvif.ver10.schema.StreamSetup streamSetup,
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * Create the OSD.
     */
    @WebMethod(operationName = "CreateOSD", action = "http://www.onvif.org/ver10/media/wsdl/CreateOSD")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "CreateOSDResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", partName = "parameters")
    public CreateOSDResponse createOSD(
        @WebParam(partName = "parameters", name = "CreateOSD", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        CreateOSD parameters
    );

    /**
     * This operation lists all existing video source configurations for a device. The client need not know anything about the video source configurations in order to use the command.
     */
    @WebMethod(operationName = "GetVideoSourceConfigurations", action = "http://www.onvif.org/ver10/media/wsdl/GetVideoSourceConfigurations")
    @RequestWrapper(localName = "GetVideoSourceConfigurations", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetVideoSourceConfigurations")
    @ResponseWrapper(localName = "GetVideoSourceConfigurationsResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetVideoSourceConfigurationsResponse")
    @WebResult(name = "Configurations", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
    public java.util.List<org.onvif.ver10.schema.VideoSourceConfiguration> getVideoSourceConfigurations();

    /**
     * This operation adds a VideoAnalytics configuration to an existing media profile. If a
     * configuration exists in the media profile, it will be replaced. The change shall be persistent. Adding a VideoAnalyticsConfiguration to a media profile means that streams using that media
     * profile can contain video analytics data (in the metadata) as defined by the submitted configuration reference. A profile containing only a video analytics configuration but no video source configuration is incomplete. Therefore, a client should first add a video source configuration to a profile before adding a video analytics configuration. The device can deny adding of a video analytics
     * configuration before a video source configuration.
     */
    @WebMethod(operationName = "AddVideoAnalyticsConfiguration", action = "http://www.onvif.org/ver10/media/wsdl/AddVideoAnalyticsConfiguration")
    @RequestWrapper(localName = "AddVideoAnalyticsConfiguration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.AddVideoAnalyticsConfiguration")
    @ResponseWrapper(localName = "AddVideoAnalyticsConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.AddVideoAnalyticsConfigurationResponse")
    public void addVideoAnalyticsConfiguration(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String profileToken,
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String configurationToken
    );

    /**
     * This command starts multicast streaming using a specified media profile of a device.
     * Streaming continues until StopMulticastStreaming is called for the same Profile. The
     * streaming shall continue after a reboot of the device until a StopMulticastStreaming request is
     * received. The multicast address, port and TTL are configured in the
     * VideoEncoderConfiguration, AudioEncoderConfiguration and MetadataConfiguration
     * respectively.
     */
    @WebMethod(operationName = "StartMulticastStreaming", action = "http://www.onvif.org/ver10/media/wsdl/StartMulticastStreaming")
    @RequestWrapper(localName = "StartMulticastStreaming", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.StartMulticastStreaming")
    @ResponseWrapper(localName = "StartMulticastStreamingResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.StartMulticastStreamingResponse")
    public void startMulticastStreaming(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * Synchronization points allow clients to decode and correctly use all data after the
     * synchronization point.
     * For example, if a video stream is configured with a large I-frame distance and a client loses a
     * single packet, the client does not display video until the next I-frame is transmitted. In such
     * cases, the client can request a Synchronization Point which enforces the device to add an I-Frame as soon as possible. Clients can request Synchronization Points for profiles. The device
     * shall add synchronization points for all streams associated with this profile.
     * Similarly, a synchronization point is used to get an update on full PTZ or event status through
     * the metadata stream.
     * If a video stream is associated with the profile, an I-frame shall be added to this video stream.
     * If a PTZ metadata stream is associated to the profile,
     * the PTZ position shall be repeated within the metadata stream.
     */
    @WebMethod(operationName = "SetSynchronizationPoint", action = "http://www.onvif.org/ver10/media/wsdl/SetSynchronizationPoint")
    @RequestWrapper(localName = "SetSynchronizationPoint", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.SetSynchronizationPoint")
    @ResponseWrapper(localName = "SetSynchronizationPointResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.SetSynchronizationPointResponse")
    public void setSynchronizationPoint(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * This operation adds an AudioSourceConfiguration to an existing media profile. If a
     * configuration exists in the media profile, it will be replaced. The change shall be persistent.
     */
    @WebMethod(operationName = "AddAudioSourceConfiguration", action = "http://www.onvif.org/ver10/media/wsdl/AddAudioSourceConfiguration")
    @RequestWrapper(localName = "AddAudioSourceConfiguration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.AddAudioSourceConfiguration")
    @ResponseWrapper(localName = "AddAudioSourceConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.AddAudioSourceConfigurationResponse")
    public void addAudioSourceConfiguration(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String profileToken,
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String configurationToken
    );

    /**
     * This operation adds an AudioOutputConfiguration to an existing media profile. If a configuration exists in the media profile, it will be replaced. The change shall be persistent.
     */
    @WebMethod(operationName = "AddAudioOutputConfiguration", action = "http://www.onvif.org/ver10/media/wsdl/AddAudioOutputConfiguration")
    @RequestWrapper(localName = "AddAudioOutputConfiguration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.AddAudioOutputConfiguration")
    @ResponseWrapper(localName = "AddAudioOutputConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.AddAudioOutputConfigurationResponse")
    public void addAudioOutputConfiguration(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String profileToken,
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String configurationToken
    );

    /**
     * This operation requests all the metadata configurations of the device that are compatible with a certain media profile. Each of the returned configurations shall be a valid input parameter for the AddMetadataConfiguration command on the media profile. The result varies depending on the capabilities, configurations and settings in the device.
     */
    @WebMethod(operationName = "GetCompatibleMetadataConfigurations", action = "http://www.onvif.org/ver10/media/wsdl/GetCompatibleMetadataConfigurations")
    @RequestWrapper(localName = "GetCompatibleMetadataConfigurations", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetCompatibleMetadataConfigurations")
    @ResponseWrapper(localName = "GetCompatibleMetadataConfigurationsResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetCompatibleMetadataConfigurationsResponse")
    @WebResult(name = "Configurations", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
    public java.util.List<org.onvif.ver10.schema.MetadataConfiguration> getCompatibleMetadataConfigurations(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * This operation returns the available options (supported values and ranges for metadata configuration parameters) for changing the metadata configuration.
     */
    @WebMethod(operationName = "GetMetadataConfigurationOptions", action = "http://www.onvif.org/ver10/media/wsdl/GetMetadataConfigurationOptions")
    @RequestWrapper(localName = "GetMetadataConfigurationOptions", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetMetadataConfigurationOptions")
    @ResponseWrapper(localName = "GetMetadataConfigurationOptionsResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetMetadataConfigurationOptionsResponse")
    @WebResult(name = "Options", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
    public org.onvif.ver10.schema.MetadataConfigurationOptions getMetadataConfigurationOptions(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String configurationToken,
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * This operation modifies an audio decoder configuration. The ForcePersistence flag indicates if
     * the changes shall remain after reboot of the device.
     */
    @WebMethod(operationName = "SetAudioDecoderConfiguration", action = "http://www.onvif.org/ver10/media/wsdl/SetAudioDecoderConfiguration")
    @RequestWrapper(localName = "SetAudioDecoderConfiguration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.SetAudioDecoderConfiguration")
    @ResponseWrapper(localName = "SetAudioDecoderConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.SetAudioDecoderConfigurationResponse")
    public void setAudioDecoderConfiguration(
        @WebParam(name = "Configuration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        org.onvif.ver10.schema.AudioDecoderConfiguration configuration,
        @WebParam(name = "ForcePersistence", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        boolean forcePersistence
    );

    /**
     * This operation returns the available options (supported values and ranges for audio output configuration parameters) for configuring an audio output.
     */
    @WebMethod(operationName = "GetAudioOutputConfigurationOptions", action = "http://www.onvif.org/ver10/media/wsdl/GetAudioOutputConfigurationOptions")
    @RequestWrapper(localName = "GetAudioOutputConfigurationOptions", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetAudioOutputConfigurationOptions")
    @ResponseWrapper(localName = "GetAudioOutputConfigurationOptionsResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetAudioOutputConfigurationOptionsResponse")
    @WebResult(name = "Options", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
    public org.onvif.ver10.schema.AudioOutputConfigurationOptions getAudioOutputConfigurationOptions(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String configurationToken,
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * This operation modifies a video source configuration. The ForcePersistence flag indicates if the changes shall remain after reboot of the device. Running streams using this configuration may be immediately updated according to the new settings. The changes are not guaranteed to take effect unless the client requests a new stream URI and restarts any affected stream. NVC methods for changing a running stream are out of scope for this specification.
     */
    @WebMethod(operationName = "SetVideoSourceConfiguration", action = "http://www.onvif.org/ver10/media/wsdl/SetVideoSourceConfiguration")
    @RequestWrapper(localName = "SetVideoSourceConfiguration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.SetVideoSourceConfiguration")
    @ResponseWrapper(localName = "SetVideoSourceConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.SetVideoSourceConfigurationResponse")
    public void setVideoSourceConfiguration(
        @WebParam(name = "Configuration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        org.onvif.ver10.schema.VideoSourceConfiguration configuration,
        @WebParam(name = "ForcePersistence", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        boolean forcePersistence
    );

    /**
     * This command lists all audio output configurations of a device that are compatible with a certain media profile. Each returned configuration shall be a valid input for the 
     * AddAudioOutputConfiguration command.
     */
    @WebMethod(operationName = "GetCompatibleAudioOutputConfigurations", action = "http://www.onvif.org/ver10/media/wsdl/GetCompatibleAudioOutputConfigurations")
    @RequestWrapper(localName = "GetCompatibleAudioOutputConfigurations", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetCompatibleAudioOutputConfigurations")
    @ResponseWrapper(localName = "GetCompatibleAudioOutputConfigurationsResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetCompatibleAudioOutputConfigurationsResponse")
    @WebResult(name = "Configurations", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
    public java.util.List<org.onvif.ver10.schema.AudioOutputConfiguration> getCompatibleAudioOutputConfigurations(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * This operation lists all existing video encoder configurations of a device. This command lists all configured video encoder configurations in a device. The client need not know anything apriori about the video encoder configurations in order to use the command.
     */
    @WebMethod(operationName = "GetVideoEncoderConfigurations", action = "http://www.onvif.org/ver10/media/wsdl/GetVideoEncoderConfigurations")
    @RequestWrapper(localName = "GetVideoEncoderConfigurations", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetVideoEncoderConfigurations")
    @ResponseWrapper(localName = "GetVideoEncoderConfigurationsResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetVideoEncoderConfigurationsResponse")
    @WebResult(name = "Configurations", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
    public java.util.List<org.onvif.ver10.schema.VideoEncoderConfiguration> getVideoEncoderConfigurations();

    /**
     * A video analytics configuration is modified using this command. The ForcePersistence flag
     * indicates if the changes shall remain after reboot of the device or not. Running streams using
     * this configuration shall be immediately updated according to the new settings. Otherwise
     * inconsistencies can occur between the scene description processed by the rule engine and
     * the notifications produced by analytics engine and rule engine which reference the very same
     * video analytics configuration token.
     */
    @WebMethod(operationName = "SetVideoAnalyticsConfiguration", action = "http://www.onvif.org/ver10/media/wsdl/SetVideoAnalyticsConfiguration")
    @RequestWrapper(localName = "SetVideoAnalyticsConfiguration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.SetVideoAnalyticsConfiguration")
    @ResponseWrapper(localName = "SetVideoAnalyticsConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.SetVideoAnalyticsConfigurationResponse")
    public void setVideoAnalyticsConfiguration(
        @WebParam(name = "Configuration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        org.onvif.ver10.schema.VideoAnalyticsConfiguration configuration,
        @WebParam(name = "ForcePersistence", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        boolean forcePersistence
    );

    /**
     * This operation returns the available options  (supported values and ranges for audio encoder configuration parameters) when the audio encoder parameters are
     * reconfigured.
     */
    @WebMethod(operationName = "GetAudioEncoderConfigurationOptions", action = "http://www.onvif.org/ver10/media/wsdl/GetAudioEncoderConfigurationOptions")
    @RequestWrapper(localName = "GetAudioEncoderConfigurationOptions", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetAudioEncoderConfigurationOptions")
    @ResponseWrapper(localName = "GetAudioEncoderConfigurationOptionsResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetAudioEncoderConfigurationOptionsResponse")
    @WebResult(name = "Options", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
    public org.onvif.ver10.schema.AudioEncoderConfigurationOptions getAudioEncoderConfigurationOptions(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String configurationToken,
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * Any endpoint can ask for the existing media profiles of a device using the GetProfiles
     * command. Pre-configured or dynamically configured profiles can be retrieved using this
     * command. This command lists all configured profiles in a device. The client does not need to
     * know the media profile in order to use the command.
     */
    @WebMethod(operationName = "GetProfiles", action = "http://www.onvif.org/ver10/media/wsdl/GetProfiles")
    @RequestWrapper(localName = "GetProfiles", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetProfiles")
    @ResponseWrapper(localName = "GetProfilesResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetProfilesResponse")
    @WebResult(name = "Profiles", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
    public java.util.List<org.onvif.ver10.schema.Profile> getProfiles();

    /**
     * This operation adds a Metadata configuration to an existing media profile. If a configuration exists in the media profile, it will be replaced. The change shall be persistent. Adding a MetadataConfiguration to a Profile means that streams using that profile contain metadata. Metadata can consist of events, PTZ status, and/or video analytics data.
     */
    @WebMethod(operationName = "AddMetadataConfiguration", action = "http://www.onvif.org/ver10/media/wsdl/AddMetadataConfiguration")
    @RequestWrapper(localName = "AddMetadataConfiguration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.AddMetadataConfiguration")
    @ResponseWrapper(localName = "AddMetadataConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.AddMetadataConfigurationResponse")
    public void addMetadataConfiguration(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String profileToken,
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String configurationToken
    );

    /**
     * This operation modifies an audio encoder configuration. The ForcePersistence flag indicates if
     * the changes shall remain after reboot of the device. Running streams using this configuration may be immediately updated
     * according to the new settings. The changes are not guaranteed to take effect unless the client
     * requests a new stream URI and restarts any affected streams. NVC methods for changing a
     * running stream are out of scope for this specification.
     */
    @WebMethod(operationName = "SetAudioEncoderConfiguration", action = "http://www.onvif.org/ver10/media/wsdl/SetAudioEncoderConfiguration")
    @RequestWrapper(localName = "SetAudioEncoderConfiguration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.SetAudioEncoderConfiguration")
    @ResponseWrapper(localName = "SetAudioEncoderConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.SetAudioEncoderConfigurationResponse")
    public void setAudioEncoderConfiguration(
        @WebParam(name = "Configuration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        org.onvif.ver10.schema.AudioEncoderConfiguration configuration,
        @WebParam(name = "ForcePersistence", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        boolean forcePersistence
    );

    /**
     * This operation returns the available options  (supported values and ranges for video source configuration parameters) when the video source parameters are
     * reconfigured If a video source configuration is specified, the options shall concern that
     * particular configuration. If a media profile is specified, the options shall be compatible with
     * that media profile.
     */
    @WebMethod(operationName = "GetVideoSourceConfigurationOptions", action = "http://www.onvif.org/ver10/media/wsdlGetVideoSourceConfigurationOptions/")
    @RequestWrapper(localName = "GetVideoSourceConfigurationOptions", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetVideoSourceConfigurationOptions")
    @ResponseWrapper(localName = "GetVideoSourceConfigurationOptionsResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetVideoSourceConfigurationOptionsResponse")
    @WebResult(name = "Options", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
    public org.onvif.ver10.schema.VideoSourceConfigurationOptions getVideoSourceConfigurationOptions(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String configurationToken,
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * The GetGuaranteedNumberOfVideoEncoderInstances command can be used to request the
     * minimum number of guaranteed video encoder instances (applications) per Video Source
     * Configuration.
     */
    @WebMethod(operationName = "GetGuaranteedNumberOfVideoEncoderInstances", action = "http://www.onvif.org/ver10/media/wsdl/GetGuaranteedNumberOfVideoEncoderInstances")
    @RequestWrapper(localName = "GetGuaranteedNumberOfVideoEncoderInstances", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetGuaranteedNumberOfVideoEncoderInstances")
    @ResponseWrapper(localName = "GetGuaranteedNumberOfVideoEncoderInstancesResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetGuaranteedNumberOfVideoEncoderInstancesResponse")
    public void getGuaranteedNumberOfVideoEncoderInstances(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String configurationToken,
        @WebParam(mode = WebParam.Mode.OUT, name = "TotalNumber", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        javax.xml.ws.Holder<java.lang.Integer> totalNumber,
        @WebParam(mode = WebParam.Mode.OUT, name = "JPEG", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        javax.xml.ws.Holder<java.lang.Integer> jpeg,
        @WebParam(mode = WebParam.Mode.OUT, name = "H264", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        javax.xml.ws.Holder<java.lang.Integer> h264,
        @WebParam(mode = WebParam.Mode.OUT, name = "MPEG4", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        javax.xml.ws.Holder<java.lang.Integer> mpeg4
    );

    /**
     * If the profile token is already known, a profile can be fetched through the GetProfile command.
     */
    @WebMethod(operationName = "GetProfile", action = "http://www.onvif.org/ver10/media/wsdlGetProfile/")
    @RequestWrapper(localName = "GetProfile", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetProfile")
    @ResponseWrapper(localName = "GetProfileResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetProfileResponse")
    @WebResult(name = "Profile", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
    public org.onvif.ver10.schema.Profile getProfile(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * The GetVideoAnalyticsConfiguration command fetches the video analytics configuration if the video analytics token is known.
     */
    @WebMethod(operationName = "GetVideoAnalyticsConfiguration", action = "http://www.onvif.org/ver10/media/wsdl/GetVideoAnalyticsConfiguration")
    @RequestWrapper(localName = "GetVideoAnalyticsConfiguration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetVideoAnalyticsConfiguration")
    @ResponseWrapper(localName = "GetVideoAnalyticsConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetVideoAnalyticsConfigurationResponse")
    @WebResult(name = "Configuration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
    public org.onvif.ver10.schema.VideoAnalyticsConfiguration getVideoAnalyticsConfiguration(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String configurationToken
    );

    /**
     * This command lists all existing AudioOutputConfigurations of a device. The NVC need not know anything apriori about the audio configurations to use this command.
     */
    @WebMethod(operationName = "GetAudioOutputConfigurations", action = "http://www.onvif.org/ver10/media/wsdl/GetAudioOutputConfigurations")
    @RequestWrapper(localName = "GetAudioOutputConfigurations", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetAudioOutputConfigurations")
    @ResponseWrapper(localName = "GetAudioOutputConfigurationsResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetAudioOutputConfigurationsResponse")
    @WebResult(name = "Configurations", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
    public java.util.List<org.onvif.ver10.schema.AudioOutputConfiguration> getAudioOutputConfigurations();

    /**
     * Set the OSD
     */
    @WebMethod(operationName = "SetOSD", action = "http://www.onvif.org/ver10/media/wsdl/SetOSD")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "SetOSDResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", partName = "parameters")
    public SetOSDResponse setOSD(
        @WebParam(partName = "parameters", name = "SetOSD", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        SetOSD parameters
    );

    /**
     * This operation adds a PTZConfiguration to an existing media profile. If a configuration exists
     * in the media profile, it will be replaced. The change shall be persistent. Adding a PTZConfiguration to a media profile means that streams using that media profile can
     * contain PTZ status (in the metadata), and that the media profile can be used for controlling
     * PTZ movement.
     */
    @WebMethod(operationName = "AddPTZConfiguration", action = "http://www.onvif.org/ver10/media/wsdl/AddPTZConfiguration")
    @RequestWrapper(localName = "AddPTZConfiguration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.AddPTZConfiguration")
    @ResponseWrapper(localName = "AddPTZConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.AddPTZConfigurationResponse")
    public void addPTZConfiguration(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String profileToken,
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String configurationToken
    );

    /**
     * This command lists all available physical audio outputs of the device.
     */
    @WebMethod(operationName = "GetAudioOutputs", action = "http://www.onvif.org/ver10/media/wsdl/GetAudioOutputs")
    @RequestWrapper(localName = "GetAudioOutputs", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetAudioOutputs")
    @ResponseWrapper(localName = "GetAudioOutputsResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetAudioOutputsResponse")
    @WebResult(name = "AudioOutputs", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
    public java.util.List<org.onvif.ver10.schema.AudioOutput> getAudioOutputs();

    /**
     * This operation requests all video analytic configurations of the device that are compatible with a certain media profile. Each of the returned configurations shall be a valid input parameter for the AddVideoAnalyticsConfiguration command on the media profile. The result varies depending on the capabilities, configurations and settings in the device.
     */
    @WebMethod(operationName = "GetCompatibleVideoAnalyticsConfigurations", action = "http://www.onvif.org/ver10/media/wsdl/GetCompatibleVideoAnalyticsConfigurations")
    @RequestWrapper(localName = "GetCompatibleVideoAnalyticsConfigurations", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetCompatibleVideoAnalyticsConfigurations")
    @ResponseWrapper(localName = "GetCompatibleVideoAnalyticsConfigurationsResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetCompatibleVideoAnalyticsConfigurationsResponse")
    @WebResult(name = "Configurations", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
    public java.util.List<org.onvif.ver10.schema.VideoAnalyticsConfiguration> getCompatibleVideoAnalyticsConfigurations(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * This operation lists all video analytics configurations of a device. This command lists all configured video analytics in a device. The client need not know anything apriori about the video analytics in order to use the command.
     */
    @WebMethod(operationName = "GetVideoAnalyticsConfigurations", action = "http://www.onvif.org/ver10/media/wsdl/GetVideoAnalyticsConfigurations")
    @RequestWrapper(localName = "GetVideoAnalyticsConfigurations", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetVideoAnalyticsConfigurations")
    @ResponseWrapper(localName = "GetVideoAnalyticsConfigurationsResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetVideoAnalyticsConfigurationsResponse")
    @WebResult(name = "Configurations", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
    public java.util.List<org.onvif.ver10.schema.VideoAnalyticsConfiguration> getVideoAnalyticsConfigurations();

    /**
     * This operation requests all audio source configurations of the device that are compatible with a certain media profile. Each of the returned configurations shall be a valid input parameter for the AddAudioEncoderConfiguration command on the media profile. The result varies depending on the capabilities, configurations and settings in the device.
     */
    @WebMethod(operationName = "GetCompatibleAudioSourceConfigurations", action = "http://www.onvif.org/ver10/media/wsdl/GetCompatibleAudioSourceConfigurations")
    @RequestWrapper(localName = "GetCompatibleAudioSourceConfigurations", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetCompatibleAudioSourceConfigurations")
    @ResponseWrapper(localName = "GetCompatibleAudioSourceConfigurationsResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetCompatibleAudioSourceConfigurationsResponse")
    @WebResult(name = "Configurations", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
    public java.util.List<org.onvif.ver10.schema.AudioSourceConfiguration> getCompatibleAudioSourceConfigurations(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * A device returns the information for current video source mode and settable video source modes of specified video source. A device that indicates a capability of  VideoSourceModes shall support this command.
     */
    @WebMethod(operationName = "GetVideoSourceModes", action = "http://www.onvif.org/ver10/media/wsdl/GetVideoSourceModes")
    @RequestWrapper(localName = "GetVideoSourceModes", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetVideoSourceModes")
    @ResponseWrapper(localName = "GetVideoSourceModesResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetVideoSourceModesResponse")
    @WebResult(name = "VideoSourceModes", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
    public java.util.List<org.onvif.ver10.media.wsdl.VideoSourceMode> getVideoSourceModes(
        @WebParam(name = "VideoSourceToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String videoSourceToken
    );

    /**
     * This operation returns the available options (supported values and ranges for audio source configuration parameters) when the audio source parameters are
     * reconfigured. If an audio source configuration is specified, the options shall concern that
     * particular configuration. If a media profile is specified, the options shall be compatible with
     * that media profile.
     */
    @WebMethod(operationName = "GetAudioSourceConfigurationOptions", action = "http://www.onvif.org/ver10/media/wsdl/GetAudioSourceConfigurationOptions")
    @RequestWrapper(localName = "GetAudioSourceConfigurationOptions", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetAudioSourceConfigurationOptions")
    @ResponseWrapper(localName = "GetAudioSourceConfigurationOptionsResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetAudioSourceConfigurationOptionsResponse")
    @WebResult(name = "Options", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
    public org.onvif.ver10.schema.AudioSourceConfigurationOptions getAudioSourceConfigurationOptions(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String configurationToken,
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * This command lists all available physical audio inputs of the device.
     */
    @WebMethod(operationName = "GetAudioSources", action = "http://www.onvif.org/ver10/media/wsdl/GetAudioSources")
    @RequestWrapper(localName = "GetAudioSources", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetAudioSources")
    @ResponseWrapper(localName = "GetAudioSourcesResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetAudioSourcesResponse")
    @WebResult(name = "AudioSources", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
    public java.util.List<org.onvif.ver10.schema.AudioSource> getAudioSources();

    /**
     * This command lists all available physical video inputs of the device.
     */
    @WebMethod(operationName = "GetVideoSources", action = "http://www.onvif.org/ver10/media/wsdlGetVideoSources/")
    @RequestWrapper(localName = "GetVideoSources", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetVideoSources")
    @ResponseWrapper(localName = "GetVideoSourcesResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetVideoSourcesResponse")
    @WebResult(name = "VideoSources", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
    public java.util.List<org.onvif.ver10.schema.VideoSource> getVideoSources();

    /**
     * If the audio decoder configuration token is already known, the decoder configuration can be fetched through the GetAudioDecoderConfiguration command.
     */
    @WebMethod(operationName = "GetAudioDecoderConfiguration", action = "http://www.onvif.org/ver10/media/wsdl/GetAudioDecoderConfiguration")
    @RequestWrapper(localName = "GetAudioDecoderConfiguration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetAudioDecoderConfiguration")
    @ResponseWrapper(localName = "GetAudioDecoderConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetAudioDecoderConfigurationResponse")
    @WebResult(name = "Configuration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
    public org.onvif.ver10.schema.AudioDecoderConfiguration getAudioDecoderConfiguration(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String configurationToken
    );

    /**
     * The GetAudioSourceConfiguration command fetches the audio source configurations if the audio source configuration token is already known. An
     */
    @WebMethod(operationName = "GetAudioSourceConfiguration", action = "http://www.onvif.org/ver10/media/wsdl/GetAudioSourceConfiguration")
    @RequestWrapper(localName = "GetAudioSourceConfiguration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetAudioSourceConfiguration")
    @ResponseWrapper(localName = "GetAudioSourceConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetAudioSourceConfigurationResponse")
    @WebResult(name = "Configuration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
    public org.onvif.ver10.schema.AudioSourceConfiguration getAudioSourceConfiguration(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String configurationToken
    );

    /**
     * This operation requests all the video source configurations of the device that are compatible
     * with a certain media profile. Each of the returned configurations shall be a valid input
     * parameter for the AddVideoSourceConfiguration command on the media profile. The result
     * will vary depending on the capabilities, configurations and settings in the device.
     */
    @WebMethod(operationName = "GetCompatibleVideoSourceConfigurations", action = "http://www.onvif.org/ver10/media/wsdl/GetCompatibleVideoSourceConfigurations")
    @RequestWrapper(localName = "GetCompatibleVideoSourceConfigurations", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetCompatibleVideoSourceConfigurations")
    @ResponseWrapper(localName = "GetCompatibleVideoSourceConfigurationsResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetCompatibleVideoSourceConfigurationsResponse")
    @WebResult(name = "Configurations", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
    public java.util.List<org.onvif.ver10.schema.VideoSourceConfiguration> getCompatibleVideoSourceConfigurations(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * This operation lists all the audio decoder configurations of the device that are compatible with a certain media profile. Each of the returned configurations shall be a valid input parameter for the AddAudioDecoderConfiguration command on the media profile.
     */
    @WebMethod(operationName = "GetCompatibleAudioDecoderConfigurations", action = "http://www.onvif.org/ver10/media/wsdl/GetCompatibleAudioDecoderConfigurations")
    @RequestWrapper(localName = "GetCompatibleAudioDecoderConfigurations", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetCompatibleAudioDecoderConfigurations")
    @ResponseWrapper(localName = "GetCompatibleAudioDecoderConfigurationsResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetCompatibleAudioDecoderConfigurationsResponse")
    @WebResult(name = "Configurations", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
    public java.util.List<org.onvif.ver10.schema.AudioDecoderConfiguration> getCompatibleAudioDecoderConfigurations(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * This operation adds a VideoEncoderConfiguration to an existing media profile. If a
     * configuration exists in the media profile, it will be replaced. The change shall be persistent. A device shall
     * support adding a compatible VideoEncoderConfiguration to a Profile containing a VideoSourceConfiguration and shall
     * support streaming video data of such a profile.
     * 			
     */
    @WebMethod(operationName = "AddVideoEncoderConfiguration", action = "http://www.onvif.org/ver10/media/wsdl/AddVideoEncoderConfiguration")
    @RequestWrapper(localName = "AddVideoEncoderConfiguration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.AddVideoEncoderConfiguration")
    @ResponseWrapper(localName = "AddVideoEncoderConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.AddVideoEncoderConfigurationResponse")
    public void addVideoEncoderConfiguration(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String profileToken,
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String configurationToken
    );

    /**
     * This operation lists all existing metadata configurations. The client need not know anything apriori about the metadata in order to use the command.
     */
    @WebMethod(operationName = "GetMetadataConfigurations", action = "http://www.onvif.org/ver10/media/wsdl/GetMetadataConfigurations")
    @RequestWrapper(localName = "GetMetadataConfigurations", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetMetadataConfigurations")
    @ResponseWrapper(localName = "GetMetadataConfigurationsResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetMetadataConfigurationsResponse")
    @WebResult(name = "Configurations", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
    public java.util.List<org.onvif.ver10.schema.MetadataConfiguration> getMetadataConfigurations();

    /**
     * This operation modifies an audio source configuration. The ForcePersistence flag indicates if
     * the changes shall remain after reboot of the device. Running streams using this configuration
     * may be immediately updated according to the new settings. The changes are not guaranteed
     * to take effect unless the client requests a new stream URI and restarts any affected stream
     * NVC methods for changing a running stream are out of scope for this specification.
     */
    @WebMethod(operationName = "SetAudioSourceConfiguration", action = "http://www.onvif.org/ver10/media/wsdl/SetAudioSourceConfiguration")
    @RequestWrapper(localName = "SetAudioSourceConfiguration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.SetAudioSourceConfiguration")
    @ResponseWrapper(localName = "SetAudioSourceConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.SetAudioSourceConfigurationResponse")
    public void setAudioSourceConfiguration(
        @WebParam(name = "Configuration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        org.onvif.ver10.schema.AudioSourceConfiguration configuration,
        @WebParam(name = "ForcePersistence", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        boolean forcePersistence
    );

    /**
     * Delete the OSD.
     */
    @WebMethod(operationName = "DeleteOSD", action = "http://www.onvif.org/ver10/media/wsdl/DeleteOSD")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "DeleteOSDResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", partName = "parameters")
    public DeleteOSDResponse deleteOSD(
        @WebParam(partName = "parameters", name = "DeleteOSD", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        DeleteOSD parameters
    );

    /**
     * This operation removes an AudioDecoderConfiguration from an existing media profile. If the media profile does not contain an AudioDecoderConfiguration, the operation has no effect. The removal shall be persistent.
     */
    @WebMethod(operationName = "RemoveAudioDecoderConfiguration", action = "http://www.onvif.org/ver10/media/wsdl/RemoveAudioDecoderConfiguration")
    @RequestWrapper(localName = "RemoveAudioDecoderConfiguration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.RemoveAudioDecoderConfiguration")
    @ResponseWrapper(localName = "RemoveAudioDecoderConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.RemoveAudioDecoderConfigurationResponse")
    public void removeAudioDecoderConfiguration(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * This operation deletes a profile. This change shall always be persistent. Deletion of a profile is only possible for non-fixed profiles
     */
    @WebMethod(operationName = "DeleteProfile", action = "http://www.onvif.org/ver10/media/wsdl/DeleteProfile")
    @RequestWrapper(localName = "DeleteProfile", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.DeleteProfile")
    @ResponseWrapper(localName = "DeleteProfileResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.DeleteProfileResponse")
    public void deleteProfile(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * This operation lists all the video encoder configurations of the device that are compatible with a certain media profile. Each of the returned configurations shall be a valid input parameter for the AddVideoEncoderConfiguration command on the media profile. The result will vary depending on the capabilities, configurations and settings in the device.
     */
    @WebMethod(operationName = "GetCompatibleVideoEncoderConfigurations", action = "http://www.onvif.org/ver10/media/wsdl/GetCompatibleVideoEncoderConfigurations")
    @RequestWrapper(localName = "GetCompatibleVideoEncoderConfigurations", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetCompatibleVideoEncoderConfigurations")
    @ResponseWrapper(localName = "GetCompatibleVideoEncoderConfigurationsResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetCompatibleVideoEncoderConfigurationsResponse")
    @WebResult(name = "Configurations", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
    public java.util.List<org.onvif.ver10.schema.VideoEncoderConfiguration> getCompatibleVideoEncoderConfigurations(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * The GetMetadataConfiguration command fetches the metadata configuration if the metadata token is known.
     */
    @WebMethod(operationName = "GetMetadataConfiguration", action = "http://www.onvif.org/ver10/media/wsdl/GetMetadataConfiguration")
    @RequestWrapper(localName = "GetMetadataConfiguration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetMetadataConfiguration")
    @ResponseWrapper(localName = "GetMetadataConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetMetadataConfigurationResponse")
    @WebResult(name = "Configuration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
    public org.onvif.ver10.schema.MetadataConfiguration getMetadataConfiguration(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String configurationToken
    );

    /**
     * This operation modifies a video encoder configuration. The ForcePersistence flag indicates if the changes shall remain after reboot of the device. Changes in the Multicast settings shall always be persistent. Running streams using this configuration may be immediately updated according to the new settings. The changes are not guaranteed to take effect unless the client requests a new stream URI and restarts any affected stream. NVC methods for changing a running stream are out of scope for this specification. SessionTimeout is provided as a hint for keeping rtsp session by a device. If necessary the device may adapt parameter values for SessionTimeout elements without returning an error. For the time between keep alive calls the client shall adhere to the timeout value signaled via RTSP.
     */
    @WebMethod(operationName = "SetVideoEncoderConfiguration", action = "http://www.onvif.org/ver10/media/wsdl/SetVideoEncoderConfiguration")
    @RequestWrapper(localName = "SetVideoEncoderConfiguration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.SetVideoEncoderConfiguration")
    @ResponseWrapper(localName = "SetVideoEncoderConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.SetVideoEncoderConfigurationResponse")
    public void setVideoEncoderConfiguration(
        @WebParam(name = "Configuration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        org.onvif.ver10.schema.VideoEncoderConfiguration configuration,
        @WebParam(name = "ForcePersistence", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        boolean forcePersistence
    );

    /**
     * This command list the audio decoding capabilities for a given profile and configuration of a
     * device.
     */
    @WebMethod(operationName = "GetAudioDecoderConfigurationOptions", action = "http://www.onvif.org/ver10/media/wsdl/GetAudioDecoderConfigurationOptions")
    @RequestWrapper(localName = "GetAudioDecoderConfigurationOptions", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetAudioDecoderConfigurationOptions")
    @ResponseWrapper(localName = "GetAudioDecoderConfigurationOptionsResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetAudioDecoderConfigurationOptionsResponse")
    @WebResult(name = "Options", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
    public org.onvif.ver10.schema.AudioDecoderConfigurationOptions getAudioDecoderConfigurationOptions(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String configurationToken,
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * Get the OSD Options.
     */
    @WebMethod(operationName = "GetOSDOptions", action = "http://www.onvif.org/ver10/media/wsdl/GetOSDOptions")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "GetOSDOptionsResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", partName = "parameters")
    public GetOSDOptionsResponse getOSDOptions(
        @WebParam(partName = "parameters", name = "GetOSDOptions", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        GetOSDOptions parameters
    );

    /**
     * This operation adds an AudioEncoderConfiguration to an existing media profile. If a 
     * configuration exists in the media profile, it will be replaced. The change shall be persistent. A device shall
     * support adding a compatible AudioEncoderConfiguration to a profile containing an AudioSourceConfiguration and shall
     * support streaming audio data of such a profile.
     * 			
     */
    @WebMethod(operationName = "AddAudioEncoderConfiguration", action = "http://www.onvif.org/ver10/media/wsdl/AddAudioEncoderConfiguration")
    @RequestWrapper(localName = "AddAudioEncoderConfiguration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.AddAudioEncoderConfiguration")
    @ResponseWrapper(localName = "AddAudioEncoderConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.AddAudioEncoderConfigurationResponse")
    public void addAudioEncoderConfiguration(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String profileToken,
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String configurationToken
    );

    /**
     * This operation adds an AudioDecoderConfiguration to an existing media profile. If a configuration exists in the media profile, it shall be replaced. The change shall be persistent.
     */
    @WebMethod(operationName = "AddAudioDecoderConfiguration", action = "http://www.onvif.org/ver10/media/wsdl/AddAudioDecoderConfiguration")
    @RequestWrapper(localName = "AddAudioDecoderConfiguration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.AddAudioDecoderConfiguration")
    @ResponseWrapper(localName = "AddAudioDecoderConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.AddAudioDecoderConfigurationResponse")
    public void addAudioDecoderConfiguration(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String profileToken,
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String configurationToken
    );

    /**
     * This operation removes a VideoAnalyticsConfiguration from an existing media profile. If the media profile does not contain a VideoAnalyticsConfiguration, the operation has no effect.
     * The removal shall be persistent.
     */
    @WebMethod(operationName = "RemoveVideoAnalyticsConfiguration", action = "http://www.onvif.org/ver10/media/wsdl/RemoveVideoAnalyticsConfiguration")
    @RequestWrapper(localName = "RemoveVideoAnalyticsConfiguration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.RemoveVideoAnalyticsConfiguration")
    @ResponseWrapper(localName = "RemoveVideoAnalyticsConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.RemoveVideoAnalyticsConfigurationResponse")
    public void removeVideoAnalyticsConfiguration(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * This operation removes a MetadataConfiguration from an existing media profile. If the media profile does not contain a MetadataConfiguration, the operation has no effect. The removal shall be persistent.
     */
    @WebMethod(operationName = "RemoveMetadataConfiguration", action = "http://www.onvif.org/ver10/media/wsdl/RemoveMetadataConfiguration")
    @RequestWrapper(localName = "RemoveMetadataConfiguration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.RemoveMetadataConfiguration")
    @ResponseWrapper(localName = "RemoveMetadataConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.RemoveMetadataConfigurationResponse")
    public void removeMetadataConfiguration(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * This operation removes an AudioOutputConfiguration from an existing media profile. If the media profile does not contain an AudioOutputConfiguration, the operation has no effect. The removal shall be persistent.
     */
    @WebMethod(operationName = "RemoveAudioOutputConfiguration", action = "http://www.onvif.org/ver10/media/wsdl/RemoveAudioOutputConfiguration")
    @RequestWrapper(localName = "RemoveAudioOutputConfiguration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.RemoveAudioOutputConfiguration")
    @ResponseWrapper(localName = "RemoveAudioOutputConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.RemoveAudioOutputConfigurationResponse")
    public void removeAudioOutputConfiguration(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * This operation lists all existing device audio encoder configurations. The client need not know anything apriori about the audio encoder configurations in order to use the command.
     */
    @WebMethod(operationName = "GetAudioEncoderConfigurations", action = "http://www.onvif.org/ver10/media/wsdl/GetAudioEncoderConfigurations")
    @RequestWrapper(localName = "GetAudioEncoderConfigurations", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetAudioEncoderConfigurations")
    @ResponseWrapper(localName = "GetAudioEncoderConfigurationsResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetAudioEncoderConfigurationsResponse")
    @WebResult(name = "Configurations", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
    public java.util.List<org.onvif.ver10.schema.AudioEncoderConfiguration> getAudioEncoderConfigurations();

    /**
     * This operation modifies a metadata configuration. The ForcePersistence flag indicates if the
     * changes shall remain after reboot of the device. Changes in the Multicast settings shall
     * always be persistent. Running streams using this configuration may be updated immediately
     * according to the new settings. The changes are not guaranteed to take effect unless the client
     * requests a new stream URI and restarts any affected streams. NVC methods for changing a
     * running stream are out of scope for this specification.
     */
    @WebMethod(operationName = "SetMetadataConfiguration", action = "http://www.onvif.org/ver10/media/wsdl/SetMetadataConfiguration")
    @RequestWrapper(localName = "SetMetadataConfiguration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.SetMetadataConfiguration")
    @ResponseWrapper(localName = "SetMetadataConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.SetMetadataConfigurationResponse")
    public void setMetadataConfiguration(
        @WebParam(name = "Configuration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        org.onvif.ver10.schema.MetadataConfiguration configuration,
        @WebParam(name = "ForcePersistence", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        boolean forcePersistence
    );

    /**
     * If the video source configuration token is already known, the video source configuration can be fetched through the GetVideoSourceConfiguration command.
     */
    @WebMethod(operationName = "GetVideoSourceConfiguration", action = "http://www.onvif.org/ver10/media/wsdl/GetVideoSourceConfiguration")
    @RequestWrapper(localName = "GetVideoSourceConfiguration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetVideoSourceConfiguration")
    @ResponseWrapper(localName = "GetVideoSourceConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetVideoSourceConfigurationResponse")
    @WebResult(name = "Configuration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
    public org.onvif.ver10.schema.VideoSourceConfiguration getVideoSourceConfiguration(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String configurationToken
    );

    /**
     * This command lists all existing AudioDecoderConfigurations of a device. The NVC need not know anything apriori about the audio decoder configurations in order to
     * use this command.
     */
    @WebMethod(operationName = "GetAudioDecoderConfigurations", action = "http://www.onvif.org/ver10/media/wsdl/GetAudioDecoderConfigurations")
    @RequestWrapper(localName = "GetAudioDecoderConfigurations", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetAudioDecoderConfigurations")
    @ResponseWrapper(localName = "GetAudioDecoderConfigurationsResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetAudioDecoderConfigurationsResponse")
    @WebResult(name = "Configurations", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
    public java.util.List<org.onvif.ver10.schema.AudioDecoderConfiguration> getAudioDecoderConfigurations();

    /**
     * This operation removes an AudioSourceConfiguration from an existing media profile. If the
     * media profile does not contain an AudioSourceConfiguration, the operation has no effect. The
     * removal shall be persistent. Audio source configurations should only be removed after removing an
     * AudioEncoderConfiguration from the media profile.
     */
    @WebMethod(operationName = "RemoveAudioSourceConfiguration", action = "http://www.onvif.org/ver10/media/wsdl/RemoveAudioSourceConfiguration")
    @RequestWrapper(localName = "RemoveAudioSourceConfiguration", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.RemoveAudioSourceConfiguration")
    @ResponseWrapper(localName = "RemoveAudioSourceConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.RemoveAudioSourceConfigurationResponse")
    public void removeAudioSourceConfiguration(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * Get the OSD.
     */
    @WebMethod(operationName = "GetOSD", action = "http://www.onvif.org/ver10/media/wsdl/GetOSD")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "GetOSDResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", partName = "parameters")
    public GetOSDResponse getOSD(
        @WebParam(partName = "parameters", name = "GetOSD", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        GetOSD parameters
    );

    /**
     * This operation lists all existing audio source configurations of a device. This command lists all audio source configurations in a device. The client need not know anything apriori about the audio source configurations in order to use the command.
     */
    @WebMethod(operationName = "GetAudioSourceConfigurations", action = "http://www.onvif.org/ver10/media/wsdlGetAudioSourceConfigurations/")
    @RequestWrapper(localName = "GetAudioSourceConfigurations", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetAudioSourceConfigurations")
    @ResponseWrapper(localName = "GetAudioSourceConfigurationsResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.GetAudioSourceConfigurationsResponse")
    @WebResult(name = "Configurations", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
    public java.util.List<org.onvif.ver10.schema.AudioSourceConfiguration> getAudioSourceConfigurations();

    /**
     * SetVideoSourceMode changes the media profile structure relating to video source for the specified video source mode. A device that indicates a capability of VideoSourceModes shall support this command. The behavior after changing the mode is not defined in this specification.
     */
    @WebMethod(operationName = "SetVideoSourceMode", action = "http://www.onvif.org/ver10/media/wsdl/SetVideoSourceMode")
    @RequestWrapper(localName = "SetVideoSourceMode", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.SetVideoSourceMode")
    @ResponseWrapper(localName = "SetVideoSourceModeResponse", targetNamespace = "http://www.onvif.org/ver10/media/wsdl", className = "org.onvif.ver10.media.wsdl.SetVideoSourceModeResponse")
    @WebResult(name = "Reboot", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
    public boolean setVideoSourceMode(
        @WebParam(name = "VideoSourceToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String videoSourceToken,
        @WebParam(name = "VideoSourceModeToken", targetNamespace = "http://www.onvif.org/ver10/media/wsdl")
        java.lang.String videoSourceModeToken
    );
}
