package org.onvif.ver10.media.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-02-20T00:14:59.632+01:00
 * Generated source version: 3.1.5
 * 
 */
@WebServiceClient(name = "MediaService", 
                  wsdlLocation = "file:/home/flavio/workspace_bosc/onvif/onvif-ws-client/src/main/cxf/ver10/media/wsdl/media.wsdl",
                  targetNamespace = "http://www.onvif.org/ver10/media/wsdl") 
public class MediaService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.onvif.org/ver10/media/wsdl", "MediaService");
    public final static QName MediaPort = new QName("http://www.onvif.org/ver10/media/wsdl", "MediaPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/flavio/workspace_bosc/onvif/onvif-ws-client/src/main/cxf/ver10/media/wsdl/media.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MediaService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/flavio/workspace_bosc/onvif/onvif-ws-client/src/main/cxf/ver10/media/wsdl/media.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MediaService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MediaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MediaService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public MediaService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MediaService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MediaService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns Media
     */
    @WebEndpoint(name = "MediaPort")
    public Media getMediaPort() {
        return super.getPort(MediaPort, Media.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Media
     */
    @WebEndpoint(name = "MediaPort")
    public Media getMediaPort(WebServiceFeature... features) {
        return super.getPort(MediaPort, Media.class, features);
    }

}
