package org.onvif.ver20.media.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-02-20T00:14:51.567+01:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://www.onvif.org/ver20/media/wsdl", name = "Media2")
@XmlSeeAlso({org.oasis_open.docs.wsrf.bf_2.ObjectFactory.class, ObjectFactory.class, org.w3._2004._08.xop.include.ObjectFactory.class, org.onvif.ver10.schema.ObjectFactory.class, org.oasis_open.docs.wsn.b_2.ObjectFactory.class, org.oasis_open.docs.wsn.t_1.ObjectFactory.class, org.w3._2003._05.soap_envelope.ObjectFactory.class, org.w3._2005._05.xmlmime.ObjectFactory.class})
public interface Media2 {

    /**
     * A device returns the information for current video source mode and settable video source modes of specified video source. A device that indicates a capability of  VideoSourceModes shall support this command.
     */
    @WebMethod(operationName = "GetVideoSourceModes", action = "http://www.onvif.org/ver20/media/wsdl/GetVideoSourceModes")
    @RequestWrapper(localName = "GetVideoSourceModes", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.GetVideoSourceModes")
    @ResponseWrapper(localName = "GetVideoSourceModesResponse", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.GetVideoSourceModesResponse")
    @WebResult(name = "VideoSourceModes", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
    public java.util.List<org.onvif.ver20.media.wsdl.VideoSourceMode> getVideoSourceModes(
        @WebParam(name = "VideoSourceToken", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String videoSourceToken
    );

    /**
     * Returns the capabilities of the media service. The result is returned in a typed answer.
     */
    @WebMethod(operationName = "GetServiceCapabilities", action = "http://www.onvif.org/ver20/media/wsdl/GetServiceCapabilities")
    @RequestWrapper(localName = "GetServiceCapabilities", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.GetServiceCapabilities")
    @ResponseWrapper(localName = "GetServiceCapabilitiesResponse2", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.GetServiceCapabilitiesResponse2")
    @WebResult(name = "Capabilities", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
    public org.onvif.ver20.media.wsdl.Capabilities2 getServiceCapabilities();

    /**
     * This operation returns the available options (supported values and ranges for video encoder 
     * 				configuration parameters) when the video encoder parameters are reconfigured. 
     * 				For JPEG, MPEG4 and H264 extension elements have been defined that provide additional information. A device must provide the 
     * 				XxxOption information for all encodings supported and should additionally provide the corresponding XxxOption2 information.
     * 				This response contains the available video encoder configuration options. If a video encoder configuration is specified, 
     * 				the options shall concern that particular configuration. If a media profile is specified, the options shall be 
     * 				compatible with that media profile. If no tokens are specified, the options shall be considered generic for the device.
     * 			
     */
    @WebMethod(operationName = "GetVideoEncoderConfigurationOptions", action = "http://www.onvif.org/ver20/media/wsdl/GetVideoEncoderConfigurationOptions")
    @RequestWrapper(localName = "GetVideoEncoderConfigurationOptions", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.GetConfiguration")
    @ResponseWrapper(localName = "GetVideoEncoderConfigurationOptionsResponse", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.GetVideoEncoderConfigurationOptionsResponse")
    @WebResult(name = "Options", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
    public java.util.List<org.onvif.ver10.schema.VideoEncoder2ConfigurationOptions> getVideoEncoderConfigurationOptions(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String configurationToken,
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * This operation returns the available options (supported values and ranges for audio source configuration parameters) when the audio source parameters are
     * 				reconfigured. If an audio source configuration is specified, the options shall concern that
     * 				particular configuration. If a media profile is specified, the options shall be compatible with
     * 				that media profile.
     */
    @WebMethod(operationName = "GetAudioSourceConfigurationOptions", action = "http://www.onvif.org/ver20/media/wsdl/GetAudioSourceConfigurationOptions")
    @RequestWrapper(localName = "GetAudioSourceConfigurationOptions", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.GetConfiguration")
    @ResponseWrapper(localName = "GetAudioSourceConfigurationOptionsResponse", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.GetAudioSourceConfigurationOptionsResponse")
    @WebResult(name = "Options", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
    public org.onvif.ver10.schema.AudioSourceConfigurationOptions getAudioSourceConfigurationOptions(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String configurationToken,
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * Get the OSD.
     */
    @WebMethod(operationName = "GetOSDs", action = "http://www.onvif.org/ver20/media/wsdl/GetOSDs")
    @RequestWrapper(localName = "GetOSDs", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.GetOSDs")
    @ResponseWrapper(localName = "GetOSDsResponse", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.GetOSDsResponse")
    @WebResult(name = "OSD", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
    public org.onvif.ver10.schema.OSDConfiguration getOSDs(
        @WebParam(name = "OSDToken", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String osdToken,
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String configurationToken
    );

    /**
     * This operation creates a new media profile. 
     * 				A created profile created via this method may be deleted via the DeleteProfile method.
     * 				Optionally Configurations can be assinged to the profile on creation. For details regarding profile assignement
     * 				check also the method AddConfiguration.
     * 			
     */
    @WebMethod(operationName = "CreateProfile", action = "http://www.onvif.org/ver20/media/wsdl/CreateProfile")
    @RequestWrapper(localName = "CreateProfile", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.CreateProfile")
    @ResponseWrapper(localName = "CreateProfileResponse", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.CreateProfileResponse")
    @WebResult(name = "Token", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
    public java.lang.String createProfile(
        @WebParam(name = "Name", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String name,
        @WebParam(name = "Configuration", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.util.List<org.onvif.ver20.media.wsdl.ConfigurationRef> configuration
    );

    /**
     * By default this operation lists all existing audio output configurations for a device. Provide a profile token to list only configurations that are compatible with the profile. If a configuration token is provided only a single configuration will be returned.
     */
    @WebMethod(operationName = "GetAudioOutputConfigurations", action = "http://www.onvif.org/ver20/media/wsdl/GetAudioOutputConfigurations")
    @RequestWrapper(localName = "GetAudioOutputConfigurations", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.GetConfiguration")
    @ResponseWrapper(localName = "GetAudioOutputConfigurationsResponse", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.GetAudioOutputConfigurationsResponse")
    @WebResult(name = "Configurations", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
    public java.util.List<org.onvif.ver10.schema.AudioOutputConfiguration> getAudioOutputConfigurations(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String configurationToken,
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * Set the OSD
     */
    @WebMethod(operationName = "SetOSD", action = "http://www.onvif.org/ver20/media/wsdl/SetOSD")
    @RequestWrapper(localName = "SetOSD", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.SetOSD")
    @ResponseWrapper(localName = "SetConfigurationResponse", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.SetConfigurationResponse")
    public void setOSD(
        @WebParam(name = "OSD", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        org.onvif.ver10.schema.OSDConfiguration osd
    );

    /**
     * This command stops multicast streaming using a specified media profile of a device
     */
    @WebMethod(operationName = "StopMulticastStreaming", action = "http://www.onvif.org/ver20/media/wsdl/StopMulticastStreaming")
    @RequestWrapper(localName = "StopMulticastStreaming", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.StartStopMulticastStreaming")
    @ResponseWrapper(localName = "StartStopMulticastStreamingResponse", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.StartStopMulticastStreamingResponse")
    public void stopMulticastStreaming(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * This command list the audio decoding capabilities for a given profile and configuration of a
     * 				device.
     */
    @WebMethod(operationName = "GetAudioDecoderConfigurationOptions", action = "http://www.onvif.org/ver20/media/wsdl/GetAudioDecoderConfigurationOptions")
    @RequestWrapper(localName = "GetAudioDecoderConfigurationOptions", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.GetConfiguration")
    @ResponseWrapper(localName = "GetAudioDecoderConfigurationOptionsResponse", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.GetAudioDecoderConfigurationOptionsResponse")
    @WebResult(name = "Options", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
    public java.util.List<org.onvif.ver10.schema.AudioEncoder2ConfigurationOptions> getAudioDecoderConfigurationOptions(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String configurationToken,
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * This operation modifies an audio output configuration.
     */
    @WebMethod(operationName = "SetAudioOutputConfiguration", action = "http://www.onvif.org/ver20/media/wsdl/SetAudioOutputConfiguration")
    @RequestWrapper(localName = "SetAudioOutputConfiguration", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.SetAudioOutputConfiguration")
    @ResponseWrapper(localName = "SetConfigurationResponse", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.SetConfigurationResponse")
    public void setAudioOutputConfiguration(
        @WebParam(name = "Configuration", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        org.onvif.ver10.schema.AudioOutputConfiguration configuration
    );

    /**
     * A client uses the GetSnapshotUri command to obtain a JPEG snapshot from the
     * device. The returned URI shall remain valid indefinitely even if the profile is changed. The
     * ValidUntilConnect, ValidUntilReboot and Timeout Parameter shall be set accordingly
     * (ValidUntilConnect=false, ValidUntilReboot=false, timeout=PT0S). The URI can be used for
     * acquiring a JPEG image through a HTTP GET operation. The image encoding will always be
     * JPEG regardless of the encoding setting in the media profile. The Jpeg settings
     * (like resolution or quality) may be taken from the profile if suitable. The provided
     * image will be updated automatically and independent from calls to GetSnapshotUri.
     */
    @WebMethod(operationName = "GetSnapshotUri", action = "http://www.onvif.org/ver20/media/wsdl/GetSnapshotUri")
    @RequestWrapper(localName = "GetSnapshotUri", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.GetSnapshotUri")
    @ResponseWrapper(localName = "GetSnapshotUriResponse", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.GetSnapshotUriResponse")
    @WebResult(name = "Uri", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
    public java.lang.String getSnapshotUri(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * Get the OSD Options.
     */
    @WebMethod(operationName = "GetOSDOptions", action = "http://www.onvif.org/ver20/media/wsdl/GetOSDOptions")
    @RequestWrapper(localName = "GetOSDOptions", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.GetOSDOptions")
    @ResponseWrapper(localName = "GetOSDOptionsResponse", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.GetOSDOptionsResponse")
    @WebResult(name = "OSDOptions", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
    public org.onvif.ver10.schema.OSDConfigurationOptions getOSDOptions(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String configurationToken
    );

    /**
     * This operation modifies an audio source configuration. Running streams using this configuration
     * 				may be immediately updated according to the new settings. The changes are not guaranteed
     * 				to take effect unless the client requests a new stream URI and restarts any affected stream
     * 				NVC methods for changing a running stream are out of scope for this specification.
     */
    @WebMethod(operationName = "SetAudioSourceConfiguration", action = "http://www.onvif.org/ver20/media/wsdl/SetAudioSourceConfiguration")
    @RequestWrapper(localName = "SetAudioSourceConfiguration", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.SetAudioSourceConfiguration")
    @ResponseWrapper(localName = "SetConfigurationResponse", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.SetConfigurationResponse")
    public void setAudioSourceConfiguration(
        @WebParam(name = "Configuration", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        org.onvif.ver10.schema.AudioSourceConfiguration configuration
    );

    /**
     * Delete the OSD.
     */
    @WebMethod(operationName = "DeleteOSD", action = "http://www.onvif.org/ver20/media/wsdl/DeleteOSD")
    @RequestWrapper(localName = "DeleteOSD", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.DeleteOSD")
    @ResponseWrapper(localName = "SetConfigurationResponse", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.SetConfigurationResponse")
    public void deleteOSD(
        @WebParam(name = "OSDToken", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String osdToken
    );

    /**
     * This operation deletes a profile. Deletion of a profile is only possible for non-fixed profiles
     */
    @WebMethod(operationName = "DeleteProfile", action = "http://www.onvif.org/ver20/media/wsdl/DeleteProfile")
    @RequestWrapper(localName = "DeleteProfile", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.DeleteProfile")
    @ResponseWrapper(localName = "DeleteProfileResponse", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.DeleteProfileResponse")
    public void deleteProfile(
        @WebParam(name = "Token", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String token
    );

    /**
     * This operation modifies a video encoder configuration. Running streams using this configuration may be immediately updated according to the new settings. The changes are not guaranteed to take effect unless the client requests a new stream URI and restarts any affected stream. NVC methods for changing a running stream are out of scope for this specification. SessionTimeout is provided as a hint for keeping rtsp session by a device. If necessary the device may adapt parameter values for SessionTimeout elements without returning an error. For the time between keep alive calls the client shall adhere to the timeout value signaled via RTSP.
     */
    @WebMethod(operationName = "SetVideoEncoderConfiguration", action = "http://www.onvif.org/ver20/media/wsdl/SetVideoEncoderConfiguration")
    @RequestWrapper(localName = "SetVideoEncoderConfiguration", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.SetVideoEncoderConfiguration")
    @ResponseWrapper(localName = "SetConfigurationResponse", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.SetConfigurationResponse")
    public void setVideoEncoderConfiguration(
        @WebParam(name = "Configuration", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        org.onvif.ver10.schema.VideoEncoder2Configuration configuration
    );

    /**
     * By default this operation lists all existing metadata configurations for a device. Provide a profile token to list only configurations that are compatible with the profile. If a configuration token is provided only a single configuration will be returned.
     */
    @WebMethod(operationName = "GetMetadataConfigurations", action = "http://www.onvif.org/ver20/media/wsdl/GetMetadataConfigurations")
    @RequestWrapper(localName = "GetMetadataConfigurations", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.GetConfiguration")
    @ResponseWrapper(localName = "GetMetadataConfigurationsResponse", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.GetMetadataConfigurationsResponse")
    @WebResult(name = "Configurations", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
    public java.util.List<org.onvif.ver10.schema.MetadataConfiguration> getMetadataConfigurations(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String configurationToken,
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * By default this operation lists all existing video analytics configurations for a device. Provide a profile token to list only configurations that are compatible with the profile. If a configuration token is provided only a single configuration will be returned.
     */
    @WebMethod(operationName = "GetAnalyticsConfigurations", action = "http://www.onvif.org/ver20/media/wsdl/GetAnalyticsConfigurations")
    @RequestWrapper(localName = "GetAnalyticsConfigurations", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.GetConfiguration")
    @ResponseWrapper(localName = "GetAnalyticsConfigurationsResponse", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.GetAnalyticsConfigurationsResponse")
    @WebResult(name = "Configurations", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
    public java.util.List<org.onvif.ver10.schema.VideoAnalyticsConfiguration> getAnalyticsConfigurations(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String configurationToken,
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * This command starts multicast streaming using a specified media profile of a device.
     * 				Streaming continues until StopMulticastStreaming is called for the same Profile. The
     * 				streaming shall continue after a reboot of the device until a StopMulticastStreaming request is
     * 				received. The multicast address, port and TTL are configured in the
     * 				VideoEncoderConfiguration, AudioEncoderConfiguration and MetadataConfiguration
     * 				respectively.
     */
    @WebMethod(operationName = "StartMulticastStreaming", action = "http://www.onvif.org/ver20/media/wsdl/StartMulticastStreaming")
    @RequestWrapper(localName = "StartMulticastStreaming", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.StartStopMulticastStreaming")
    @ResponseWrapper(localName = "StartStopMulticastStreamingResponse", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.StartStopMulticastStreamingResponse")
    public void startMulticastStreaming(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * Synchronization points allow clients to decode and correctly use all data after the
     * synchronization point.
     * For example, if a video stream is configured with a large I-frame distance and a client loses a
     * single packet, the client does not display video until the next I-frame is transmitted. In such
     * cases, the client can request a Synchronization Point which enforces the device to add an I-Frame as soon as possible. Clients can request Synchronization Points for profiles. The device
     * shall add synchronization points for all streams associated with this profile.
     * Similarly, a synchronization point is used to get an update on full PTZ or event status through
     * the metadata stream.
     * If a video stream is associated with the profile, an I-frame shall be added to this video stream.
     * If a PTZ metadata stream is associated to the profile,
     * the PTZ position shall be repeated within the metadata stream.
     */
    @WebMethod(operationName = "SetSynchronizationPoint", action = "http://www.onvif.org/ver20/media/wsdl/SetSynchronizationPoint")
    @RequestWrapper(localName = "SetSynchronizationPoint", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.SetSynchronizationPoint")
    @ResponseWrapper(localName = "SetSynchronizationPointResponse", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.SetSynchronizationPointResponse")
    public void setSynchronizationPoint(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * This operation removes the listed configurations from an existing media profile. If the
     * 				media profile does not contain one of the listed configurations that item shall be ignored. 
     * 				Note that the token is only required for the OSD items.
     */
    @WebMethod(operationName = "RemoveConfiguration", action = "http://www.onvif.org/ver20/media/wsdl/RemoveConfiguration")
    @RequestWrapper(localName = "RemoveConfiguration", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.RemoveConfiguration")
    @ResponseWrapper(localName = "RemoveConfigurationResponse", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.RemoveConfigurationResponse")
    public void removeConfiguration(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String profileToken,
        @WebParam(name = "Configuration", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.util.List<org.onvif.ver20.media.wsdl.ConfigurationRef> configuration
    );

    /**
     * Create the OSD.
     */
    @WebMethod(operationName = "CreateOSD", action = "http://www.onvif.org/ver20/media/wsdl/CreateOSD")
    @RequestWrapper(localName = "CreateOSD", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.CreateOSD")
    @ResponseWrapper(localName = "CreateOSDResponse", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.CreateOSDResponse")
    @WebResult(name = "OSDToken", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
    public java.lang.String createOSD(
        @WebParam(name = "OSD", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        org.onvif.ver10.schema.OSDConfiguration osd
    );

    /**
     * By default this operation lists all existing video source configurations for a device. Provide a profile token to list only configurations that are compatible with the profile. If a configuration token is provided only a single configuration will be returned.
     */
    @WebMethod(operationName = "GetVideoSourceConfigurations", action = "http://www.onvif.org/ver20/media/wsdl/GetVideoSourceConfigurations")
    @RequestWrapper(localName = "GetVideoSourceConfigurations", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.GetConfiguration")
    @ResponseWrapper(localName = "GetVideoSourceConfigurationsResponse", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.GetVideoSourceConfigurationsResponse")
    @WebResult(name = "Configurations", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
    public java.util.List<org.onvif.ver10.schema.VideoSourceConfiguration> getVideoSourceConfigurations(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String configurationToken,
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * This operation requests a URI that can be used to initiate a live media stream using RTSP as
     * 				the control protocol. The returned URI shall remain valid indefinitely even if the profile is changed. 
     * 				Defined stream types are
     * 				 
     * 				If a multicast stream is requested the VideoEncoderConfiguration, AudioEncoderConfiguration and MetadataConfiguration element inside the corresponding 
     * 				media profile must be configured with valid multicast settings.
     * 				For full compatibility with other ONVIF services a device should not generate Uris longer than
     * 				128 octets.
     */
    @WebMethod(operationName = "GetStreamUri", action = "http://www.onvif.org/ver20/media/wsdl/GetStreamUri")
    @RequestWrapper(localName = "GetStreamUri", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.GetStreamUri")
    @ResponseWrapper(localName = "GetStreamUriResponse", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.GetStreamUriResponse")
    @WebResult(name = "Uri", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
    public java.lang.String getStreamUri(
        @WebParam(name = "Protocol", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String protocol,
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * By default this operation lists all existing audio source configurations for a device. Provide a profile token to list only configurations that are compatible with the profile. If a configuration token is provided only a single configuration will be returned.
     */
    @WebMethod(operationName = "GetAudioSourceConfigurations", action = "http://www.onvif.org/ver20/media/wsdlGetAudioSourceConfigurations/")
    @RequestWrapper(localName = "GetAudioSourceConfigurations", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.GetConfiguration")
    @ResponseWrapper(localName = "GetAudioSourceConfigurationsResponse", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.GetAudioSourceConfigurationsResponse")
    @WebResult(name = "Configurations", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
    public java.util.List<org.onvif.ver10.schema.AudioSourceConfiguration> getAudioSourceConfigurations(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String configurationToken,
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * This operation adds one or more Configurations to an existing media profile. If a
     * configuration exists in the media profile, it will be replaced. A device shall
     * support adding a compatible Configuration to a Profile containing a VideoSourceConfiguration and shall
     * support streaming video data of such a profile.
     * 				Note that OSD elements must be added via the CreateOSD command.
     * 			
     */
    @WebMethod(operationName = "AddConfiguration", action = "http://www.onvif.org/ver20/media/wsdl/AddConfiguration")
    @RequestWrapper(localName = "AddConfiguration", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.AddConfiguration")
    @ResponseWrapper(localName = "AddConfigurationResponse", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.AddConfigurationResponse")
    public void addConfiguration(
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String profileToken,
        @WebParam(name = "Name", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String name,
        @WebParam(name = "Configuration", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.util.List<org.onvif.ver20.media.wsdl.ConfigurationRef> configuration
    );

    /**
     * SetVideoSourceMode changes the media profile structure relating to video source for the specified video source mode. A device that indicates a capability of VideoSourceModes shall support this command. The behavior after changing the mode is not defined in this specification.
     */
    @WebMethod(operationName = "SetVideoSourceMode", action = "http://www.onvif.org/ver20/media/wsdl/SetVideoSourceMode")
    @RequestWrapper(localName = "SetVideoSourceMode", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.SetVideoSourceMode")
    @ResponseWrapper(localName = "SetVideoSourceModeResponse", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.SetVideoSourceModeResponse")
    @WebResult(name = "Reboot", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
    public boolean setVideoSourceMode(
        @WebParam(name = "VideoSourceToken", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String videoSourceToken,
        @WebParam(name = "VideoSourceModeToken", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String videoSourceModeToken
    );

    /**
     * This operation returns the available options  (supported values and ranges for audio encoder configuration parameters) when the audio encoder parameters are
     * 				reconfigured.
     */
    @WebMethod(operationName = "GetAudioEncoderConfigurationOptions", action = "http://www.onvif.org/ver20/media/wsdl/GetAudioEncoderConfigurationOptions")
    @RequestWrapper(localName = "GetAudioEncoderConfigurationOptions", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.GetConfiguration")
    @ResponseWrapper(localName = "GetAudioEncoderConfigurationOptionsResponse", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.GetAudioEncoderConfigurationOptionsResponse")
    @WebResult(name = "Options", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
    public java.util.List<org.onvif.ver10.schema.AudioEncoder2ConfigurationOptions> getAudioEncoderConfigurationOptions(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String configurationToken,
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * Retrieve the profile with the specified token or all defined media profiles. If no configuration types are defined only the profile names and token are returned.
     * 				In case of provided configuration types all information regarding these types is returned. Pass "All" to get all available configurations.
     */
    @WebMethod(operationName = "GetProfiles", action = "http://www.onvif.org/ver20/media/wsdl/GetProfiles")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "GetProfilesResponse", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", partName = "parameters")
    public GetProfilesResponse getProfiles(
        @WebParam(partName = "parameters", name = "GetProfiles", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        GetProfiles parameters
    );

    /**
     * This operation modifies an audio encoder configuration. Running streams using this configuration may be immediately updated
     * 				according to the new settings. The changes are not guaranteed to take effect unless the client
     * 				requests a new stream URI and restarts any affected streams. NVC methods for changing a
     * 				running stream are out of scope for this specification.
     */
    @WebMethod(operationName = "SetAudioEncoderConfiguration", action = "http://www.onvif.org/ver20/media/wsdl/SetAudioEncoderConfiguration")
    @RequestWrapper(localName = "SetAudioEncoderConfiguration", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.SetAudioEncoderConfiguration")
    @ResponseWrapper(localName = "SetConfigurationResponse", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.SetConfigurationResponse")
    public void setAudioEncoderConfiguration(
        @WebParam(name = "Configuration", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        org.onvif.ver10.schema.AudioEncoder2Configuration configuration
    );

    /**
     * This operation returns the available options  (supported values and ranges for video source configuration parameters) when the video source parameters are
     * 				reconfigured If a video source configuration is specified, the options shall concern that
     * 				particular configuration. If a media profile is specified, the options shall be compatible with
     * 				that media profile.
     */
    @WebMethod(operationName = "GetVideoSourceConfigurationOptions", action = "http://www.onvif.org/ver20/media/wsdlGetVideoSourceConfigurationOptions/")
    @RequestWrapper(localName = "GetVideoSourceConfigurationOptions", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.GetConfiguration")
    @ResponseWrapper(localName = "GetVideoSourceConfigurationOptionsResponse", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.GetVideoSourceConfigurationOptionsResponse")
    @WebResult(name = "Options", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
    public org.onvif.ver10.schema.VideoSourceConfigurationOptions getVideoSourceConfigurationOptions(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String configurationToken,
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * This operation modifies a video source configuration. Running streams using this configuration may be immediately updated according to the new settings. The changes are not guaranteed to take effect unless the client requests a new stream URI and restarts any affected stream. NVC methods for changing a running stream are out of scope for this specification.
     */
    @WebMethod(operationName = "SetVideoSourceConfiguration", action = "http://www.onvif.org/ver20/media/wsdl/SetVideoSourceConfiguration")
    @RequestWrapper(localName = "SetVideoSourceConfiguration", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.SetVideoSourceConfiguration")
    @ResponseWrapper(localName = "SetConfigurationResponse", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.SetConfigurationResponse")
    public void setVideoSourceConfiguration(
        @WebParam(name = "Configuration", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        org.onvif.ver10.schema.VideoSourceConfiguration configuration
    );

    /**
     * By default this operation lists all existing audio decoder configurations for a device. Provide a profile token to list only configurations that are compatible with the profile. If a configuration token is provided only a single configuration will be returned.
     */
    @WebMethod(operationName = "GetAudioDecoderConfigurations", action = "http://www.onvif.org/ver20/media/wsdl/GetAudioDecoderConfigurations")
    @RequestWrapper(localName = "GetAudioDecoderConfigurations", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.GetConfiguration")
    @ResponseWrapper(localName = "GetAudioDecoderConfigurationsResponse", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.GetAudioDecoderConfigurationsResponse")
    @WebResult(name = "Configurations", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
    public java.util.List<org.onvif.ver10.schema.AudioDecoderConfiguration> getAudioDecoderConfigurations(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String configurationToken,
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * By default this operation lists all existing video encoder configurations for a device. Provide a profile token to list only configurations that are compatible with the profile. If a configuration token is provided only a single configuration will be returned.
     */
    @WebMethod(operationName = "GetVideoEncoderConfigurations", action = "http://www.onvif.org/ver20/media/wsdl/GetVideoEncoderConfigurations")
    @RequestWrapper(localName = "GetVideoEncoderConfigurations", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.GetConfiguration")
    @ResponseWrapper(localName = "GetVideoEncoderConfigurationsResponse", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.GetVideoEncoderConfigurationsResponse")
    @WebResult(name = "Configurations", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
    public java.util.List<org.onvif.ver10.schema.VideoEncoder2Configuration> getVideoEncoderConfigurations(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String configurationToken,
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * By default this operation lists all existing audio encoder configurations for a device. Provide a profile token to list only configurations that are compatible with the profile. If a configuration token is provided only a single configuration will be returned.
     */
    @WebMethod(operationName = "GetAudioEncoderConfigurations", action = "http://www.onvif.org/ver20/media/wsdl/GetAudioEncoderConfigurations")
    @RequestWrapper(localName = "GetAudioEncoderConfigurations", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.GetConfiguration")
    @ResponseWrapper(localName = "GetAudioEncoderConfigurationsResponse", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.GetAudioEncoderConfigurationsResponse")
    @WebResult(name = "Configurations", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
    public java.util.List<org.onvif.ver10.schema.AudioEncoder2Configuration> getAudioEncoderConfigurations(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String configurationToken,
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * This operation returns the available options (supported values and ranges for metadata configuration parameters) for changing the metadata configuration.
     */
    @WebMethod(operationName = "GetMetadataConfigurationOptions", action = "http://www.onvif.org/ver20/media/wsdl/GetMetadataConfigurationOptions")
    @RequestWrapper(localName = "GetMetadataConfigurationOptions", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.GetConfiguration")
    @ResponseWrapper(localName = "GetMetadataConfigurationOptionsResponse", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.GetMetadataConfigurationOptionsResponse")
    @WebResult(name = "Options", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
    public org.onvif.ver10.schema.MetadataConfigurationOptions getMetadataConfigurationOptions(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String configurationToken,
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String profileToken
    );

    /**
     * This operation modifies a metadata configuration. Running streams using this configuration may be updated immediately
     * 				according to the new settings. The changes are not guaranteed to take effect unless the client
     * 				requests a new stream URI and restarts any affected streams. NVC methods for changing a
     * 				running stream are out of scope for this specification.
     */
    @WebMethod(operationName = "SetMetadataConfiguration", action = "http://www.onvif.org/ver20/media/wsdl/SetMetadataConfiguration")
    @RequestWrapper(localName = "SetMetadataConfiguration", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.SetMetadataConfiguration")
    @ResponseWrapper(localName = "SetConfigurationResponse", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.SetConfigurationResponse")
    public void setMetadataConfiguration(
        @WebParam(name = "Configuration", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        org.onvif.ver10.schema.MetadataConfiguration configuration
    );

    /**
     * This operation modifies an audio decoder configuration.
     */
    @WebMethod(operationName = "SetAudioDecoderConfiguration", action = "http://www.onvif.org/ver20/media/wsdl/SetAudioDecoderConfiguration")
    @RequestWrapper(localName = "SetAudioDecoderConfiguration", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.SetAudioDecoderConfiguration")
    @ResponseWrapper(localName = "SetConfigurationResponse", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.SetConfigurationResponse")
    public void setAudioDecoderConfiguration(
        @WebParam(name = "Configuration", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        org.onvif.ver10.schema.AudioDecoderConfiguration configuration
    );

    /**
     * This operation returns the available options (supported values and ranges for audio output configuration parameters) for configuring an audio output.
     */
    @WebMethod(operationName = "GetAudioOutputConfigurationOptions", action = "http://www.onvif.org/ver20/media/wsdl/GetAudioOutputConfigurationOptions")
    @RequestWrapper(localName = "GetAudioOutputConfigurationOptions", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.GetConfiguration")
    @ResponseWrapper(localName = "GetAudioOutputConfigurationOptionsResponse", targetNamespace = "http://www.onvif.org/ver20/media/wsdl", className = "org.onvif.ver20.media.wsdl.GetAudioOutputConfigurationOptionsResponse")
    @WebResult(name = "Options", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
    public org.onvif.ver10.schema.AudioOutputConfigurationOptions getAudioOutputConfigurationOptions(
        @WebParam(name = "ConfigurationToken", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String configurationToken,
        @WebParam(name = "ProfileToken", targetNamespace = "http://www.onvif.org/ver20/media/wsdl")
        java.lang.String profileToken
    );
}
