package org.onvif.ver20.media.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-02-20T00:14:51.579+01:00
 * Generated source version: 3.1.5
 * 
 */
@WebServiceClient(name = "Media2Service", 
                  wsdlLocation = "file:/home/flavio/workspace_bosc/onvif/onvif-ws-client/src/main/cxf/ver20/media/wsdl/media.wsdl",
                  targetNamespace = "http://www.onvif.org/ver20/media/wsdl") 
public class Media2Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.onvif.org/ver20/media/wsdl", "Media2Service");
    public final static QName Media2Port = new QName("http://www.onvif.org/ver20/media/wsdl", "Media2Port");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/flavio/workspace_bosc/onvif/onvif-ws-client/src/main/cxf/ver20/media/wsdl/media.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Media2Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/flavio/workspace_bosc/onvif/onvif-ws-client/src/main/cxf/ver20/media/wsdl/media.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Media2Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Media2Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Media2Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public Media2Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Media2Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Media2Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns Media2
     */
    @WebEndpoint(name = "Media2Port")
    public Media2 getMedia2Port() {
        return super.getPort(Media2Port, Media2.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Media2
     */
    @WebEndpoint(name = "Media2Port")
    public Media2 getMedia2Port(WebServiceFeature... features) {
        return super.getPort(Media2Port, Media2.class, features);
    }

}
